name: zeyquorra
description: AI-powered career guidance app for Ugandan students
version: 1.0.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^1.10.5
  provider: ^6.0.5
  flutter_spinkit: ^5.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
